### ISSUE TITLE
ViewModelFactory

### ISSUE THREAD

**Issue by AnadolStudio** [Ch0rtik/IntervalApp#5]
https://github.com/Ch0rtik/IntervalApp/blob/418e0aaee7adefea3dff71be0b49293e400f0487/app/src/main/java/com/kosmokamikaze/intervalapp/viewmodel/quiz/QuizViewModelFactory.kt#L10-L17

https://github.com/Ch0rtik/IntervalApp/blob/418e0aaee7adefea3dff71be0b49293e400f0487/app/src/main/java/com/kosmokamikaze/intervalapp/viewmodel/menu/MenuViewModelFactory.kt#L7-L13

Зачем создавать две отдельных фабрики для двух VM, фабрика должна быть одна, на то она и фабрика.
Нужно создать одну фабрику для создания VM

**Comment by Ch0rtik** [comment]
Создал одну ViewModelFactory

**Comment by Ch0rtik** [comment]
Fixed
